### ISSUE TITLE
App Store Launch Checklist

### ISSUE THREAD

**Issue by bndkt** [bndkt/sharemystack#114]
## App/Features
- [ ] Ability to delete stacks (https://github.com/bndkt/sharemystack/issues/117)
- [x] OG images for share links
- [x] Login to Canny via Share My Stack app (currently only via website & Twitter login)
- [x] Shareable image of stacks
- [x] Add privacy and support pages on website
- [x] Add footer/imprint on website
- [x] Prepare data migration thread for test users (profiles only, no stacks/picks/stars)

## Content
- [x] Add all tool website/AppStore links
- [x] Add a few more featured stacks

## Marketing
- [x] Add to projects page on my blog
- [x] Prepare blog post about WatermelonDB/Supabase
- [ ] Prepare launch blog post
- [x] Prepare LinkedIn post
- [x] Schedule Twitter thread
- [x] Prepare and schedule PH launch
- [x] Prepare email list in ConvertKit
- [x] Prepare launch email

## Nice to have
- [x] Fix and enable dark mode
